server:
  port: 9999
  servlet:
    session:
      timeout: 30s

spring:
  datasource:
    #url: jdbc:mysql://localhost:3306/non_jpa_db?serverTimezone=UTC&useSSL=false
    url:  jdbc:mysql://localhost:3306/jpa_db?serverTimezone=UTC&useSSL=false
    username: khweb
    password: khweb@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MYSQL8Dialect


  jpa:
    open-in-view: false
    database: mysql
    show-sql: true
    generrate-ddl: true
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG